- name: Runnig the resource collecting script.
  script: scripts/report.sh
  args:
    executable: /bin/bash

- name: Getting the HOSTNAME
  shell: hostname
  register: result

- name: Fetching the output to local system
  fetch:
    dest: "./reports/{{ group_names[0] }}/{{inventory_hostname}}.txt"
    fail_on_missing: yes
    flat: yes
    src: "/tmp/{{ result.stdout }}.txt"
    validate_checksum: yes
